### ISSUE TITLE
npm start script not working with node v8

### ISSUE THREAD

**Issue by wachsarah** [hfg-gmuend/hfg-documentation-generator#3]
throws error  -  "cwd" must be a string 
worked with: downgrade to node v6

**Comment by fhirner** [comment]
works with node v7.10.0

**Comment by fhirner** [comment]
error log for v8.1.2
```
~/D/hfg-documentation-generator (master|✔) $ npm start                                                        (14s 865ms) 

> hfg-documentation-generator@0.0.0 start /Users/fh/Desktop/hfg-documentation-generator
> parallelshell 'npm run dev' 'npm run watch-content'

child_process.js:400
    throw new TypeError('"cwd" must be a string');
    ^

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:400:11)
    at exports.spawn (child_process.js:485:38)
    at /Users/fh/Desktop/hfg-documentation-generator/node_modules/parallelshell/index.js:104:17
    at Array.forEach (native)
    at Object.<anonymous> (/Users/fh/Desktop/hfg-documentation-generator/node_modules/parallelshell/index.js:100:6)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hfg-documentation-generator@0.0.0 start: `parallelshell 'npm run dev' 'npm run watch-content'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hfg-documentation-generator@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fh/.npm/_logs/2017-06-21T13_10_53_053Z-debug.log
~/D/hfg-documentation-generator (master|✔) $ node --version                                                   (1) (678ms) 
v8.1.2

```

**Comment by fhirner** [comment]
temporary fix for nodev8:

`./hfg-documentation-generator/node_modules/parallelshell/index.js`
line 105
change `cwd: process.cwd,` to `cwd: process.cwd(),`

**Comment by b-g** [comment]
@fhirner Thanks for the quick hack/fix! Or simply don't go with node 8 ... 

The problem is https://github.com/keithamus/parallelshell#version-compatibility-notes

> Version compatibility of parallelshell
> v2.0.0 is compatible with Node < 8
> v3.x.x is compatible with Node >= 8
